env:
  - CODECOV_TOKEN='d2d0d3db-98bd-4add-8ab8-782003116ae9'
jobs:
  include:
    - language: node_js
      node_js:
        - 16
      before_script:
        - npm install
      script:
        - npm test
      after_success:
        - nyc report --reporter=text-lcov > coverage.lcov
        - codecov -cF javascript -f coverage.lcov
    - language: python
      python:
        - "3.9"
      before_script:
        - pip install -r requirements.txt
        - python ktc/convertor.py
      script:
        - coverage run -m pytest test
        - mypy ktc
      after_success:
        - codecov -cF python -f .coverage