env:
  - CODECOV_TOKEN='d2d0d3db-98bd-4add-8ab8-782003116ae9'
jobs:
  include:
    - language: python
      python:
        - "3.9"
      before_script:
        - pip install -r requirements.txt
        - python app/convertor.py
      script:
        - nosetests --with-coverage test/*.py
        - mypy app/*.py
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js:
        - 16
      before_script:
        - npm install
      script:
        - npm test
      after_success:
        - codecov