jobs:
  include:
    language: python
      python: "3.9"
      install:
        - pip install -r requirements.txt
      before_script:
        - python app/convertor.py
      script:
        - nosetests --with-coverage test/*.py
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    language: node_js
      node_js: 16
      install:
        - npm install
        - npm install -g codecov
      script:
        - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
        - codecov